"""Gemini-flavoured mock — different tone than Anthropic.

Used as the secondary adapter in the fallback chain. Calling code gets
two slightly different generations to choose from; tests assert the
fallback path is reachable when the primary raises `FallbackToNext`.
"""

from __future__ import annotations

import textwrap

from app.domain.listing import (
    GeneratedContent,
    ListingRequest,
    Platform,
    PropertySummary,
)

MODEL_NAME = "gemini-2.0-flash-mock"


class GeminiMockAdapter:
    @property
    def model_name(self) -> str:
        return MODEL_NAME

    def generate(self, request: ListingRequest) -> GeneratedContent:
        platform = request.platforms[0] if request.platforms else Platform.general
        p = request.property
        if platform == Platform.facebook:
            return _fb_fallback(p, request)
        return _generic(p, platform, request)


def _money(value: float | None) -> str:
    if value is None:
        return "—"
    return f"{value:,.0f}"


def _type_th(value: str | None) -> str:
    return {
        "condo": "คอนโด",
        "house": "บ้านเดี่ยว",
        "townhouse": "ทาวน์เฮาส์",
        "land": "ที่ดิน",
        "commercial": "อาคารพาณิชย์",
    }.get((value or "").lower(), value or "ทรัพย์สิน")


def _loc(p: PropertySummary) -> str:
    parts = [p.district, p.province]
    return ", ".join(x for x in parts if x) or "Bangkok"


def _fb_fallback(p: PropertySummary, req: ListingRequest) -> GeneratedContent:
    """Facebook fallback — slightly different word order; tests assert primary-fail path."""
    t = _type_th(p.property_type)
    return GeneratedContent(
        platform=Platform.facebook,
        title=f"รวมรายการ ขาย{t} ({p.district or 'Bangkok'})",
        description=textwrap.dedent(
            f"""
            (Generated by Gemini fallback — primary unavailable.)

            📦 {t}
            📍 {_loc(p)}
            💸 ฿{_money(p.price)}
            📐 {p.size_sqm or "—"} ตร.ม.
            🛏 {p.bedrooms or "—"} / 🚿 {p.bathrooms or "—"}
            """
        ).strip(),
        hashtags=["#fallback", "#gemini", "#listing", "#ขาย", "#Bangkok", "#อสังหา"],
        seo_keywords=[],
        ai_model=MODEL_NAME,
        prompt_used="facebook-fallback",
    )


def _generic(p: PropertySummary, platform: Platform, req: ListingRequest) -> GeneratedContent:
    t = _type_th(p.property_type)
    return GeneratedContent(
        platform=platform,
        title=f"{t} · {_loc(p)}",
        description=(
            f"Gemini fallback generated listing.\n\n"
            f"Type: {t}\nLocation: {_loc(p)}\nPrice: ฿{_money(p.price)}\n"
            f"Size: {p.size_sqm or '—'} sqm\nBedrooms/Bathrooms: "
            f"{p.bedrooms or '—'}/{p.bathrooms or '—'}"
        ),
        hashtags=["#gemini-fallback"],
        seo_keywords=[t, p.district or "Bangkok"],
        ai_model=MODEL_NAME,
        prompt_used="generic-fallback",
    )
